/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import org.xml.sax.Attributes;
//import static com.mycompany.mavenproject1.Lectures_q.place_prob;
import java.awt.Desktop;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ezzat
 */
public class Lectures_student extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame_q
     */
    public Lectures_student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Java_user_q = new javax.swing.JPanel();
        jPanel_Java1_user_q = new javax.swing.JPanel();
        jLabel2_q = new javax.swing.JLabel();
        jButton_JavaToJava_user_q = new javax.swing.JButton();
        jButton_JavaPlay_q = new javax.swing.JButton();
        jSeparator6_q1 = new javax.swing.JSeparator();
        jButton_RemoveJava_q = new javax.swing.JButton();
        jComboBox_java_q = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Java_user_q.setMinimumSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout jPanel_Java_user_qLayout = new javax.swing.GroupLayout(jPanel_Java_user_q);
        jPanel_Java_user_q.setLayout(jPanel_Java_user_qLayout);
        jPanel_Java_user_qLayout.setHorizontalGroup(
            jPanel_Java_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel_Java_user_qLayout.setVerticalGroup(
            jPanel_Java_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_Java1_user_q.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2_q.setBackground(new java.awt.Color(87, 212, 195));
        jLabel2_q.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2_q.setForeground(new java.awt.Color(87, 212, 195));
        jLabel2_q.setText("Choose Lecture : ");

        jButton_JavaToJava_user_q.setBackground(new java.awt.Color(36, 47, 85));
        jButton_JavaToJava_user_q.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_JavaToJava_user_q.setForeground(new java.awt.Color(87, 212, 195));
        jButton_JavaToJava_user_q.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lecture icon.jpg"))); // NOI18N
        jButton_JavaToJava_user_q.setToolTipText("");
        jButton_JavaToJava_user_q.setBorder(null);
        jButton_JavaToJava_user_q.setBorderPainted(false);
        jButton_JavaToJava_user_q.setContentAreaFilled(false);

        jButton_JavaPlay_q.setBackground(new java.awt.Color(36, 47, 85));
        jButton_JavaPlay_q.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_JavaPlay_q.setForeground(new java.awt.Color(255, 255, 255));
        jButton_JavaPlay_q.setText("PLAY");
        jButton_JavaPlay_q.setToolTipText("");
        jButton_JavaPlay_q.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton_JavaPlay_q.setContentAreaFilled(false);
        jButton_JavaPlay_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JavaPlay_qActionPerformed(evt);
            }
        });

        jButton_RemoveJava_q.setBackground(new java.awt.Color(36, 47, 85));
        jButton_RemoveJava_q.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton_RemoveJava_q.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RemoveJava_q.setText("Open");
        jButton_RemoveJava_q.setToolTipText("");
        jButton_RemoveJava_q.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton_RemoveJava_q.setContentAreaFilled(false);
        jButton_RemoveJava_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveJava_qActionPerformed(evt);
            }
        });

        jComboBox_java_q.setBackground(new java.awt.Color(87, 212, 195));
        jComboBox_java_q.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jComboBox_java_q.setForeground(new java.awt.Color(36, 47, 85));
        jComboBox_java_q.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture 1", "Lecture 2", "Lecture 3", "Lecture 4", "Lecture 5", "Lecture 5", "Lecture 7", "Lecture 8", "Lecture 9" }));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-home-40.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Java Lectures");

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(87, 212, 195));
        jLabel2.setText("lecture slides :");

        javax.swing.GroupLayout jPanel_Java1_user_qLayout = new javax.swing.GroupLayout(jPanel_Java1_user_q);
        jPanel_Java1_user_q.setLayout(jPanel_Java1_user_qLayout);
        jPanel_Java1_user_qLayout.setHorizontalGroup(
            jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox_java_q, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_JavaToJava_user_q, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_RemoveJava_q, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jButton_JavaPlay_q, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                        .addComponent(jLabel2_q)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_Java1_user_qLayout.setVerticalGroup(
            jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_JavaToJava_user_q)
                .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_RemoveJava_q, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_Java1_user_qLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel_Java1_user_qLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_java_q, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2_q)
                            .addComponent(jButton_JavaPlay_q, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 276, Short.MAX_VALUE)
                .addComponent(jPanel_Java_user_q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 276, Short.MAX_VALUE))
            .addComponent(jPanel_Java1_user_q, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Java1_user_q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Java_user_q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RemoveJava_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveJava_qActionPerformed
      StudentA s1=new  StudentA();
                    s1.show();
                    dispose();
    }//GEN-LAST:event_jButton_RemoveJava_qActionPerformed

    private void jButton_JavaPlay_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JavaPlay_qActionPerformed

        try {
            Desktop browser=Desktop.getDesktop();
            int index=jComboBox_java_q.getSelectedIndex();
            String link;
            //            if(index<place_java)
            //            link= Files.readAllLines(Paths.get("java.txt")).get(index+1);
            //            else
            link= Files.readAllLines(Paths.get("java.txt")).get(index);
            try {
                browser.browse(new URI(link));
            } catch (URISyntaxException ex) {
                Logger.getLogger(Lectures_q.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(Lectures_q.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_JavaPlay_qActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SignInl s1=new SignInl();
                    s1.show();
                    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lectures_q.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lectures_q.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lectures_q.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lectures_q.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lectures_q().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_JavaPlay_q;
    private javax.swing.JButton jButton_JavaToJava_user_q;
    private javax.swing.JButton jButton_RemoveJava_q;
    private javax.swing.JComboBox<String> jComboBox_java_q;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_q;
    private javax.swing.JPanel jPanel_Java1_user_q;
    private javax.swing.JPanel jPanel_Java_user_q;
    private javax.swing.JSeparator jSeparator6_q1;
    // End of variables declaration//GEN-END:variables
}
