
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class loginpage extends javax.swing.JFrame {
public int x=0;
  
    public loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1l = new javax.swing.JPanel();
        jLabel1l = new javax.swing.JLabel();
        jLabel4l = new javax.swing.JLabel();
        jLabel5l = new javax.swing.JLabel();
        jPanel4l = new javax.swing.JPanel();
        usernamel = new javax.swing.JTextField();
        passwordl = new javax.swing.JPasswordField();
        jSeparator2l = new javax.swing.JSeparator();
        jSeparator1l = new javax.swing.JSeparator();
        jLabel2l = new javax.swing.JLabel();
        jLabel3l = new javax.swing.JLabel();
        jPanel2l = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3l = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jCheckBox1l = new javax.swing.JCheckBox();
        jLabel6l = new javax.swing.JLabel();
        jLabel7l = new javax.swing.JLabel();
        jLabel8l = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1l.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.1.png"))); // NOI18N

        jLabel4l.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        jLabel4l.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4l.setText("Software Engineering");

        jLabel5l.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel5l.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5l.setText("Dr.Hadeer Ahmed");

        jPanel4l.setBackground(new java.awt.Color(0, 0, 51));

        usernamel.setBackground(new java.awt.Color(0, 0, 51));
        usernamel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernamel.setForeground(new java.awt.Color(255, 255, 255));
        usernamel.setText("Username");
        usernamel.setBorder(null);
        usernamel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamelActionPerformed(evt);
            }
        });

        passwordl.setBackground(new java.awt.Color(0, 0, 51));
        passwordl.setForeground(new java.awt.Color(255, 255, 255));
        passwordl.setText("password");
        passwordl.setBorder(null);
        passwordl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordlActionPerformed(evt);
            }
        });

        jSeparator2l.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator1l.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-2.png"))); // NOI18N

        jLabel3l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-lock-100.png"))); // NOI18N

        jPanel2l.setBackground(new java.awt.Color(0, 0, 51));

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Garamond", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2lLayout = new javax.swing.GroupLayout(jPanel2l);
        jPanel2l.setLayout(jPanel2lLayout);
        jPanel2lLayout.setHorizontalGroup(
            jPanel2lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2lLayout.setVerticalGroup(
            jPanel2lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2lLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel3l.setBackground(new java.awt.Color(0, 0, 51));

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setFont(new java.awt.Font("Garamond", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3lLayout = new javax.swing.GroupLayout(jPanel3l);
        jPanel3l.setLayout(jPanel3lLayout);
        jPanel3lLayout.setHorizontalGroup(
            jPanel3lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3lLayout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3lLayout.setVerticalGroup(
            jPanel3lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3lLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCheckBox1l.setBackground(new java.awt.Color(0, 0, 51));
        jCheckBox1l.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCheckBox1l.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1l.setText("show password");
        jCheckBox1l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1lActionPerformed(evt);
            }
        });

        jLabel7l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-login-100.png"))); // NOI18N

        jLabel8l.setBackground(new java.awt.Color(153, 153, 153));
        jLabel8l.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel8l.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8l.setText("Enter Username and Password");

        javax.swing.GroupLayout jPanel4lLayout = new javax.swing.GroupLayout(jPanel4l);
        jPanel4l.setLayout(jPanel4lLayout);
        jPanel4lLayout.setHorizontalGroup(
            jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4lLayout.createSequentialGroup()
                .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4lLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jPanel2l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(jPanel3l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4lLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7l, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4lLayout.createSequentialGroup()
                                .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2l)
                                    .addComponent(jLabel3l))
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8l, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4lLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(usernamel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordl, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4lLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2l, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1l, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1l, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel4lLayout.setVerticalGroup(
            jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4lLayout.createSequentialGroup()
                .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4lLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6l)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4lLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernamel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4lLayout.createSequentialGroup()
                                .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8l, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7l, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addComponent(jLabel2l, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4lLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1l, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox1l)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4lLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3l, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel4lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Informal Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Designed by:Infinty Loop");

        javax.swing.GroupLayout jPanel1lLayout = new javax.swing.GroupLayout(jPanel1l);
        jPanel1l.setLayout(jPanel1lLayout);
        jPanel1lLayout.setHorizontalGroup(
            jPanel1lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1lLayout.createSequentialGroup()
                .addGroup(jPanel1lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1lLayout.createSequentialGroup()
                        .addComponent(jLabel1l)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1lLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1lLayout.createSequentialGroup()
                                .addGroup(jPanel1lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5l, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4l, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1lLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addComponent(jPanel4l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1lLayout.setVerticalGroup(
            jPanel1lLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1lLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4l, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1l, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5l, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String username1="Loay tamer@student.com";
               String username2="Dr_hadeer@teacher.com";
               String pass1="engineer";
               String pass2="programing";
               try{
                FileWriter fw=new FileWriter("type.txt");
                PrintWriter pw =new PrintWriter(fw);
        if(usernamel.getText().endsWith("@student.com"))
                {   
                  x=0;
                  
                }
                else if (usernamel.getText().endsWith("@teacher.com"))
                {
                x=1;
                }
                else
                {
                  JOptionPane.showMessageDialog(this,"Invalid username and password" ,"Error" , JOptionPane.ERROR_MESSAGE);

                }
        pw.println(x);
                pw.close();
            }catch(Exception e)
            {
                e.getMessage();
            }
     
       
               
             
                if((usernamel.getText().equals(username1)&&passwordl.getText().equals(pass1))||(usernamel.getText().equals(username2)&&passwordl.getText().equals(pass2)))
                
                {
                    SignInl s1=new SignInl();
                    s1.show();
                    dispose();
                }
                else 
                {
                JOptionPane.showMessageDialog(this,"Invalid username and password" ,"Error" , JOptionPane.ERROR_MESSAGE);
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordlActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_passwordlActionPerformed

    private void usernamelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernamelActionPerformed

    private void jCheckBox1lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1lActionPerformed
        // TODO add your handling code here:
         if(jCheckBox1l.isSelected())
         {passwordl.setEchoChar((char)0);}
         else
         {
         passwordl.setEchoChar('*');
         }
       
    }//GEN-LAST:event_jCheckBox1lActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1l;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1l;
    private javax.swing.JLabel jLabel2l;
    private javax.swing.JLabel jLabel3l;
    private javax.swing.JLabel jLabel4l;
    private javax.swing.JLabel jLabel5l;
    private javax.swing.JLabel jLabel6l;
    private javax.swing.JLabel jLabel7l;
    private javax.swing.JLabel jLabel8l;
    private javax.swing.JPanel jPanel1l;
    private javax.swing.JPanel jPanel2l;
    private javax.swing.JPanel jPanel3l;
    private javax.swing.JPanel jPanel4l;
    private javax.swing.JSeparator jSeparator1l;
    private javax.swing.JSeparator jSeparator2l;
    private javax.swing.JPasswordField passwordl;
    private javax.swing.JTextField usernamel;
    // End of variables declaration//GEN-END:variables
}
